[project]
name = "sub-party"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.2",
    "nuitka>=4.0",
    "pyside6>=6.10.2",
]
